Repository ninja-build/ninja, pull requests merged in 2024-05, with the labels that each got.

#2437 RealDiskInterface: Do *not* set locale to an empty string
  src/disk_interface.cc
Labels: windows, bug

#2428 Correctly handle ANSI Escape Codes in ElideMiddle, fix #713
  src/util.cc
  src/util_test.cc
Labels: frontend

#2453 Flush stdout before calling _setmode on windows
  src/status_printer.cc
Labels: windows

#2455 cmake: disable min() and max() macros in windows.h
  CMakeLists.txt
Labels: windows
