Repository ninja-build/ninja, pull requests merged in 2024-03, with the labels that each got.

#1963 Reliable ETA and progress percentage.
  doc/manual.asciidoc
  src/build.cc
  src/build_test.cc
  src/graph.h
  src/ninja.cc
  src/status.cc
  src/status.h
  src/status_test.cc
Labels: feature

#2396 graph.h: Use default initializers to remove -Worder warnings.
  src/graph.h
Labels: cleanup

#2394 Fix crash when FormatMessageA sets lpBuffer to nullptr
  src/util.cc
Labels: windows, bug
